default_platform(:ios)

platform :ios do
  desc "Build the app without signing"
  lane :build do
    build_app(
      scheme: "DemoOnMVVM",  
      skip_package_ipa: true,
      skip_codesigning: true
    )
  end
end

